// Dedicated-server engine — creates, provisions, and runs Minecraft servers next to
// the instance launcher. Resolves the right server jar per platform (Vanilla from the
// Mojang version JSON, Paper from the PaperMC API, Fabric from the Fabric server
// launcher), boots it with the exact Mojang Java runtime for that MC version, and
// streams its console. Pure Node — identical on Windows/macOS/Linux.
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawn, execFileSync } = require("child_process");
const install = require("./install");
const { getJSON, download } = require("./net");

const FABRIC_META = "https://meta.fabricmc.net/v2/versions";
// PaperMC's v2 API was retired (410 Gone); the current source of truth is the v3
// "Fill" API, which returns builds newest-first with a direct per-build download URL.
const PAPER_API = "https://fill.papermc.io/v3/projects/paper";

// A rounded accent per platform, mirroring the instance ACCENTS in index.js.
const ACCENTS = { vanilla: "#5EE6A0", paper: "#E8E4DC", fabric: "#B57BE6" };
const PLATFORMS = ["vanilla", "paper", "fabric"];
const DEFAULT_RAM_MB = 2048;

// serverId -> running child process. Module-level so start/stop/command/remove all
// reach the same live children, just like index.js's instance `running` map.
const running = {};

// ---- Paths + JSON store (servers.json in the app-data dir) ----
function serversDir(dataDir) { return path.join(dataDir, "servers"); }
function serverDir(dataDir, id) { return path.join(serversDir(dataDir), id); }
function serversFile(dataDir) { return path.join(dataDir, "servers.json"); }
function propsPath(dataDir, id) { return path.join(serverDir(dataDir, id), "server.properties"); }

function read(dataDir) { try { return JSON.parse(fs.readFileSync(serversFile(dataDir), "utf8")); } catch { return []; } }
function write(dataDir, list) { fs.writeFileSync(serversFile(dataDir), JSON.stringify(list, null, 2)); }

function platformLabel(p) { return p === "paper" ? "Paper" : p === "fabric" ? "Fabric" : "Vanilla"; }
function defaultName(platformName, mcVersion) { return `${platformLabel(platformName)} ${mcVersion}`; }

// A sane, self-hostable default server.properties. The UI edits a common subset of
// these; the rest are stock Minecraft defaults so a fresh server just runs.
function defaultProperties(name) {
  const motd = (name && name.trim()) || "A Lodestone Server";
  return [
    "#Minecraft server properties",
    "#Generated by Lodestone",
    `motd=${motd}`,
    "gamemode=survival",
    "difficulty=easy",
    "max-players=20",
    "online-mode=true",
    "pvp=true",
    "level-name=world",
    "server-port=25565",
    "view-distance=10",
    "spawn-protection=16",
    "allow-nether=true",
    "enable-command-block=false",
    "white-list=false",
    "",
  ].join("\n");
}

// ---- server.properties parse / merge (simple key=value, comments preserved) ----
function parseProps(text) {
  const out = {};
  String(text || "").split(/\r?\n/).forEach((line) => {
    if (!line || /^\s*[#!]/.test(line)) return;
    const eq = line.indexOf("=");
    if (eq < 0) return;
    const key = line.slice(0, eq).trim();
    if (key) out[key] = line.slice(eq + 1);
  });
  return out;
}

// Rewrite `text` replacing any key present in `patch` in place, then appending keys
// that weren't already there. Comments, blank lines, and untouched keys are preserved.
function mergeProps(text, patch) {
  const remaining = {};
  for (const [k, v] of Object.entries(patch || {})) remaining[k] = v;
  const lines = String(text || "").split(/\r?\n/);
  const out = lines.map((line) => {
    if (!line || /^\s*[#!]/.test(line)) return line;
    const eq = line.indexOf("=");
    if (eq < 0) return line;
    const key = line.slice(0, eq).trim();
    if (Object.prototype.hasOwnProperty.call(remaining, key)) {
      const v = remaining[key]; delete remaining[key];
      return `${key}=${v}`;
    }
    return line;
  });
  // Drop a single trailing empty line so appends stay tidy, then re-add it at the end.
  const hadTrailingBlank = out.length && out[out.length - 1] === "";
  if (hadTrailingBlank) out.pop();
  for (const [k, v] of Object.entries(remaining)) out.push(`${k}=${v}`);
  out.push("");
  return out.join("\n");
}

// ---- Server-jar resolution per platform ----
// Downloads the platform's server jar to <dir>/server.jar and returns provenance
// fields to merge onto the stored record.
async function resolveServerJar(dataDir, platformName, mcVersion, dir, onLog) {
  const dest = path.join(dir, "server.jar");

  if (platformName === "vanilla") {
    const detail = await install.resolveVersionJSON(dataDir, mcVersion, onLog);
    const srv = detail.downloads && detail.downloads.server;
    if (!srv || !srv.url) throw new Error(`Minecraft ${mcVersion} has no dedicated server download.`);
    onLog && onLog("Downloading Vanilla server jar…");
    await download(srv.url, dest, srv.sha1);
    return {};
  }

  if (platformName === "paper") {
    let builds;
    try { builds = await getJSON(`${PAPER_API}/versions/${mcVersion}/builds`); }
    catch { throw new Error(`Paper has no build for Minecraft ${mcVersion} yet.`); }
    if (!Array.isArray(builds) || !builds.length) throw new Error(`Paper has no build for Minecraft ${mcVersion} yet.`);
    // Builds come newest-first; prefer the newest STABLE build.
    const build = builds.find((b) => b.channel === "STABLE") || builds[0];
    const dl = build.downloads && (build.downloads["server:default"] || build.downloads["server:mojang"]);
    if (!dl || !dl.url) throw new Error(`Paper build ${build.id} is missing its download.`);
    onLog && onLog(`Downloading Paper build ${build.id}…`);
    await download(dl.url, dest);
    return { paperBuild: build.id };
  }

  if (platformName === "fabric") {
    const loaders = await getJSON(`${FABRIC_META}/loader/${mcVersion}`);
    if (!Array.isArray(loaders) || !loaders.length) throw new Error(`Fabric has no loader for Minecraft ${mcVersion}.`);
    const loaderVer = ((loaders.find((l) => l.loader && l.loader.stable) || loaders[0]).loader || {}).version;
    const installers = await getJSON(`${FABRIC_META}/installer`);
    if (!Array.isArray(installers) || !installers.length) throw new Error("Fabric installer metadata is unavailable.");
    const installerVer = (installers.find((i) => i.stable) || installers[0]).version;
    if (!loaderVer || !installerVer) throw new Error("Fabric loader/installer resolution failed.");
    onLog && onLog(`Downloading Fabric server launcher (loader ${loaderVer})…`);
    await download(`${FABRIC_META}/loader/${mcVersion}/${loaderVer}/${installerVer}/server/jar`, dest);
    return { fabricLoader: loaderVer, fabricInstaller: installerVer };
  }

  throw new Error(`Unknown server type "${platformName}".`);
}

// ---- Public API ----
// create({name, platform, mcVersion}) — provision a new server dir + jar + eula + props.
async function create(dataDir, { name, platform: platformName, mcVersion } = {}, { onLog } = {}) {
  if (!mcVersion) throw new Error("Pick a Minecraft version.");
  const plat = String(platformName || "vanilla").toLowerCase();
  if (!PLATFORMS.includes(plat)) throw new Error(`Unknown server type "${platformName}".`);

  const list = read(dataDir);
  const id = Math.random().toString(16).slice(2, 14);
  const dir = serverDir(dataDir, id);
  fs.mkdirSync(dir, { recursive: true });

  try {
    onLog && onLog(`Setting up a ${platformLabel(plat)} server for Minecraft ${mcVersion}…`);
    const meta = await resolveServerJar(dataDir, plat, mcVersion, dir, onLog);

    // Accept the EULA on the user's behalf so the server actually boots.
    fs.writeFileSync(path.join(dir, "eula.txt"), "eula=true\n");
    // Seed server.properties only if the jar (or a previous run) hasn't written one.
    const props = propsPath(dataDir, id);
    if (!fs.existsSync(props)) fs.writeFileSync(props, defaultProperties(name));

    const rec = {
      id,
      name: (name && name.trim()) || defaultName(plat, mcVersion),
      platform: plat,
      mcVersion,
      jar: "server.jar",
      ramMB: DEFAULT_RAM_MB,
      accent: ACCENTS[plat] || ACCENTS.vanilla,
      created: Date.now(),
      lastStarted: null,
      ...meta,
    };
    list.unshift(rec);
    write(dataDir, list);
    onLog && onLog(`${rec.name} is ready.`);
    return rec;
  } catch (e) {
    // Never leave a half-provisioned directory behind.
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch {}
    throw e;
  }
}

function list(dataDir) {
  return read(dataDir)
    .map((s) => ({ ...s, running: !!running[s.id] }))
    .sort((a, b) => (b.lastStarted || b.created) - (a.lastStarted || a.created));
}

function get(dataDir, id) {
  const rec = read(dataDir).find((s) => s.id === id);
  if (!rec) throw new Error("Server not found.");
  return { ...rec, running: !!running[id] };
}

function isRunning(id) { return !!running[id]; }

// start(id): spawn `<java> -Xmx<ram>M -jar server.jar nogui` in the server dir, track
// the child, and stream its stdout/stderr line by line via onLog. onState fires with
// "running" once launched and "stopped" (with the exit code) when the process ends.
async function start(dataDir, id, { onLog, onState, javaPath } = {}) {
  const rec = read(dataDir).find((s) => s.id === id);
  if (!rec) throw new Error("Server not found.");
  if (running[id]) return { started: true, message: "Already running." };

  const dir = serverDir(dataDir, id);
  const jar = rec.jar || "server.jar";
  const jarPath = path.join(dir, jar);
  if (!fs.existsSync(jarPath)) throw new Error("Server jar is missing. Re-create the server.");

  // The server won't boot without an accepted EULA; keep it in place.
  const eula = path.join(dir, "eula.txt");
  if (!fs.existsSync(eula)) fs.writeFileSync(eula, "eula=true\n");

  // A user-supplied Java override wins when it points at a real binary; otherwise
  // download + use the exact Mojang runtime this MC version asks for.
  let javaBinary = javaPath && fs.existsSync(javaPath) ? javaPath : null;
  if (!javaBinary) {
    onLog && onLog(`Preparing Java for Minecraft ${rec.mcVersion}…`);
    const detail = await install.resolveVersionJSON(dataDir, rec.mcVersion, onLog);
    const component = (detail.javaVersion && detail.javaVersion.component) || "jre-legacy";
    javaBinary = await install.installJava(dataDir, component, undefined, onLog);
  }

  const ram = rec.ramMB && rec.ramMB > 0 ? Math.round(rec.ramMB) : DEFAULT_RAM_MB;
  const args = [`-Xmx${ram}M`, `-Xms${Math.min(ram, 1024)}M`, "-jar", jar, "nogui"];

  onLog && onLog(`Starting ${rec.name}…`);
  const child = spawn(javaBinary, args, { cwd: dir });
  running[id] = child;
  onState && onState({ id, status: "running" });

  const stream = (data) => String(data).split(/\r?\n/).forEach((line) => line && onLog && onLog(line));
  child.stdout.on("data", stream);
  child.stderr.on("data", stream);
  child.on("exit", (code) => {
    delete running[id];
    onState && onState({ id, status: "stopped", code: code == null ? -1 : code });
  });
  child.on("error", (err) => {
    delete running[id];
    onLog && onLog("Server error: " + err.message);
    onState && onState({ id, status: "stopped", code: -1 });
  });

  // Stamp lastStarted so the list sorts by most-recently-run.
  const l2 = read(dataDir); const idx = l2.findIndex((s) => s.id === id);
  if (idx >= 0) { l2[idx].lastStarted = Date.now(); write(dataDir, l2); }

  return { started: true, message: `Starting ${rec.name}…` };
}

// stop(id): ask the server to shut down gracefully via its own `stop` command, and
// fall back to a hard kill if it hasn't exited a few seconds later.
function stop(id) {
  const child = running[id];
  if (!child) return false;
  let exited = false;
  child.once("exit", () => { exited = true; });
  try {
    child.stdin.write("stop\n");
  } catch {
    try { child.kill(); } catch {}
    return true;
  }
  setTimeout(() => { if (!exited && running[id]) { try { running[id].kill(); } catch {} } }, 12000);
  return true;
}

// command(id, cmd): pipe a console command to the running server's stdin.
function command(id, cmd) {
  const child = running[id];
  if (!child) throw new Error("Server is not running.");
  const line = String(cmd == null ? "" : cmd).replace(/[\r\n]+$/, "");
  if (!line) return false;
  child.stdin.write(line + "\n");
  return true;
}

function properties(dataDir, id) {
  read(dataDir).find((s) => s.id === id) || (() => { throw new Error("Server not found."); })();
  let text = "";
  try { text = fs.readFileSync(propsPath(dataDir, id), "utf8"); } catch {}
  return parseProps(text);
}

function setProperties(dataDir, id, patch) {
  read(dataDir).find((s) => s.id === id) || (() => { throw new Error("Server not found."); })();
  const file = propsPath(dataDir, id);
  let text = "";
  try { text = fs.readFileSync(file, "utf8"); } catch {}
  const next = mergeProps(text, patch || {});
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next);
  return parseProps(next);
}

// ---- Hosting / share info ----
// Everything a friend needs to join: the LAN join address(es), an optional Tailscale
// tailnet address, the server port, and the current online-mode flag. Pure inspection:
// nothing here mutates the server or requires it to be running.

// This machine's non-internal IPv4 addresses (skips loopback + down interfaces).
function lanAddresses() {
  const out = [];
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const addr of ifaces[name] || []) {
      // Node reports family as "IPv4" (newer) or 4 (older) depending on version.
      const isV4 = addr.family === "IPv4" || addr.family === 4;
      if (isV4 && !addr.internal && addr.address) out.push(addr.address);
    }
  }
  return out;
}

// A Tailscale tailnet address lives in the CGNAT range 100.64.0.0/10.
function isTailscaleIP(ip) {
  const m = /^100\.(\d+)\.\d+\.\d+$/.exec(String(ip || ""));
  if (!m) return false;
  const second = Number(m[1]);
  return second >= 64 && second <= 127;
}

// Resolve this machine's Tailscale IPv4, or null if it isn't on a tailnet. Tries the
// `tailscale ip -4` CLI first (PATH, then the standard install paths per OS), and falls
// back to scanning network interfaces for a 100.64.0.0/10 address. Never throws.
function tailscaleAddress() {
  const candidates = ["tailscale"];
  if (process.platform === "win32") {
    candidates.push(
      "C:\\Program Files\\Tailscale\\tailscale.exe",
      "C:\\Program Files (x86)\\Tailscale IPN\\tailscale.exe",
    );
  } else {
    candidates.push(
      "/usr/bin/tailscale", "/usr/local/bin/tailscale", "/opt/homebrew/bin/tailscale",
      "/Applications/Tailscale.app/Contents/MacOS/Tailscale",
    );
  }
  for (const bin of candidates) {
    try {
      const out = execFileSync(bin, ["ip", "-4"], { timeout: 4000, stdio: ["ignore", "pipe", "ignore"] });
      const ip = String(out).split(/\r?\n/).map((l) => l.trim()).find((l) => /^\d+\.\d+\.\d+\.\d+$/.test(l));
      if (ip) return ip;
    } catch { /* binary missing, not logged in, or timed out: try the next candidate */ }
  }
  // Fallback: an interface already carrying a tailnet IP (works even if the CLI is absent).
  return lanAddresses().find(isTailscaleIP) || null;
}

function hostingInfo(dataDir, id) {
  read(dataDir).find((s) => s.id === id) || (() => { throw new Error("Server not found."); })();
  const props = properties(dataDir, id);

  const portNum = Number(props["server-port"]);
  const port = Number.isFinite(portNum) && portNum > 0 ? Math.round(portNum) : 25565;
  const onlineMode = props["online-mode"] != null ? String(props["online-mode"]) : "true";

  // LAN join addresses. The tailnet address is surfaced on its own, so keep it out of the
  // LAN list, unless it's the only address we have, in which case never hide it.
  const all = lanAddresses();
  let lanIPs = all.filter((ip) => !isTailscaleIP(ip));
  if (!lanIPs.length) lanIPs = all;
  const lan = lanIPs.map((ip) => `${ip}:${port}`);

  const tsIP = tailscaleAddress();
  const tailscale = tsIP ? `${tsIP}:${port}` : null;

  return { port, lan, tailscale, onlineMode };
}

// setOnlineMode(id, on): flip online-mode in server.properties. Returns the new value as
// the "true"/"false" string Minecraft stores, so the UI can confirm the persisted state.
function setOnlineMode(dataDir, id, on) {
  const value = (on === true || on === "true" || on === 1 || on === "1" || on === "on") ? "true" : "false";
  const props = setProperties(dataDir, id, { "online-mode": value });
  return props["online-mode"];
}

// remove(id): stop the server first, then delete its record + directory.
function remove(dataDir, id) {
  if (running[id]) {
    try { running[id].kill(); } catch {}
    delete running[id];
  }
  write(dataDir, read(dataDir).filter((s) => s.id !== id));
  try { fs.rmSync(serverDir(dataDir, id), { recursive: true, force: true }); } catch {}
  return true;
}

module.exports = {
  create, list, get, start, stop, command, properties, setProperties, remove, isRunning,
  hostingInfo, setOnlineMode,
  // exported for tests / reuse
  parseProps, mergeProps, defaultProperties, lanAddresses, isTailscaleIP, tailscaleAddress,
  ACCENTS, PLATFORMS,
};
